### ISSUE TITLE
Idiomatic Dart (class vs top level function)?

### ISSUE THREAD

**Issue by tosh** [izolate/slugify#1]
I was wondering if it wouldn't it be more elegant to use a top level function (slugify) instead of a class that needs to be instantiated.

See my commented on reddit:

http://www.reddit.com/r/dartlang/comments/2c8191/slugify_dart_package_to_convert_a_string_into_a/cjp7ytq

I'd love your thoughts on this as I'm trying to figure out the Dart way to handle API design like this myself.

**Comment by izolate** [comment]
Hi @tosh, thank you for asking this question. You are right, due to the simplicity of this package, it makes more sense as a top-level function. I've made this change in #4, as well as updating the package to Dart 2.
