### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by JigneshWorld** [izolate/slugify#7]
Null safety is now API stable. Publish your stable packages now!
https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by mr-mmmmore** [comment]
Is there a chance that a null-safety compliant version is released soon?

This package hasn't had updates for 2 years, some clarification about the project status would be welcome!

**Comment by izolate** [comment]
@JigneshPatel23 @mr-mmmmore Thanks for bringing this to my attention. I've added the SDK constraints to enable null safety in [v2.0.0](https://pub.dev/packages/slugify/versions/2.0.0). The breaking change was introduced by fixing dart analyzer lint errors.

Until now, there hasn't been a need to update the package. If you have any feature suggestions, do let me know.

**Comment by mr-mmmmore** [comment]
I Thanks @izolate! I will use the new version in a few weeks when I migrate my app.

**Comment by mr-mmmmore** [comment]
Hi, just passing by to say that I haven't encountered any problems with the 2.0.0 in an app built with sound null safety.
